Algoritmo "ContarAte10"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 11/12/2021
Var

   contador : Inteiro

Inicio

      contador <- 1
      enquanto (contador <= 10) faca
      Escreva(contador)
      contador <- contador + 1
      fimenquanto
      


Fimalgoritmo