Algoritmo "ContarAte10"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 12/12/2021
Var
 cont : Inteiro


Inicio

      para cont <- 1 ate 10 faca
      escreva(cont,"...")
      fimpara
      escreval
      para cont <- 10 ate 1 passo -1 faca
           Escreva(cont,"...")
      fimpara

Fimalgoritmo