Algoritmo "Sequencia"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 12/12/2021
Var

   cont, cont1 : Inteiro


Inicio

      para cont <-1 ate 3 faca
           para cont1 <- 1 ate 3 faca
                Escreval(cont, cont1)
           fimpara
      fimpara


Fimalgoritmo