Algoritmo "ContarAte10"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 12/12/2021
Var

   cont : Inteiro


Inicio

      cont <- 1
      Repita
            Escreva(cont,"...")
            cont <- cont + 1
      Ate (cont > 10)


Fimalgoritmo