Algoritmo "SeuNome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 11/12/2021
Var
// Seção de Declarações das variáveis 
   nome : Caractere

Inicio

      Escreva("Digite o seu nome: ")
      leia(nome)
      Escreval("Bom dia, ",nome,", tudo bem contigo?")


Fimalgoritmo